### ISSUE TITLE
What is the aim of this middleware ?

### ISSUE THREAD

**Issue by rbecheras** [kospiotr/swagger-spec-middleware#8]
Hi @kospiotr, your module seems interesting, but I can't really see for what it is designed for.

Could you clarify it for me please ?

**Comment by kospiotr** [comment]
The aim of the middleware is to simplify creating REST services powered by the contract in the swagger spec format.
Maybe example will be better here. In the corporate environment, when you need to comunicate with another service you are using some kind of contract. In SOAP word you are using WSDL file, in RMI it's a set of interfaces and for the REST world there is WADL but more common ways of sharing such contract is RAML or Swagger for the support and addons.
The Swagger contract is a spec json file that describes method exposed by some service with types meta-information. From the consumer perspective this middleware is using ExpressJS to set up such described REST endpoints and from the hoster perspective this middleware allows to handle such REST endpoint where all parameters are aggregated by the name and converted according to the contract. Example again:
Let say you have client that is calling REST method: GET .../api/users/1/accounts?query=apple
You should have described such REST operation in the swagger spec:

```
...
"/api/users/{userId}/accounts": {
      "get": {
        "description": "Returns accounts of the user",
        "operationId": "getUserAccounts",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "type": "int32"
          },
          {
            "name": "query",
            "in": "query",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/errorModel"
            }
          }
        }
      }
      }
```
Then you can handle it:

```
swaggerSpecMiddleware.host(app, {
    spec: 'spec.json',
    handlers: {
        getUserAccounts: function(meta, userId, query){
            return ...
        }
    }

});
```

Mind that if the query is valid according to the contract both declared parameters will be converted passed to the handling method.

You may ask how it helps comparing to the traditional way of using simple http Connect server or ExpressJS or other. Well you have:
- contract that can be used as a specification
- contract that is well documented, can be used by others, can be imported by the swagger UI or other tool like SoapUI, Postman and others
- parameters are being fetched from the different sources like path chunks, quries or header, validated and converted so you don't need to pollute your business code with unnecessary ceremony

Any other questions?
